db-name: clevertec_db
spring:
  liquibase:
    enabled: true
    drop-first: true
    change-log: db.changelog/changeLog.xml
    default-schema: ${db-name}
    liquibase-schema: ${db-name}
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:

    username: root
    password: pass
    url: jdbc:mysql://localhost:3306/${db-name}?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate-ddl: true
        storage_engine: innodb
        dialect: org.hibernate.dialect.MySQL8Dialect
#          default_schema: ${db-name}

    #     wrong
    open-in-view: true
    show-sql: true
